### ISSUE TITLE
Cannot run, maybe missing some test files and configuration files

### ISSUE THREAD

**Issue by Life93** [psyai-net/CVCUDA_FaceStoreHelper-release#1]
Thank you very much for sharing the amazing work, but it seems that the project is missing some files, which prevents it from running directly. Looking forward to your response.

**Comment by FANzhaoxin666** [comment]
> , but it seems that the project is missing some files, which prevents it from running directly. Looking forward to your response.

yes, the onnx file is missing, we will upload it soon.

**Comment by Life93** [comment]
thanks.

**Comment by prakyath-07** [comment]
@FANzhaoxin666 Thanks for the repo and models. I'm not able to download the files from baidu. Is it possible to share Google Drive link?

**Comment by zhangsanfeng86** [comment]
@FANzhaoxin666   where is the file 'nvcv_python-0.3.1-cp38-cp38-linux_x86_64.whl'?

**Comment by FANzhaoxin666** [comment]
> @FANzhaoxin666 Thanks for the repo and models. I'm not able to download the files from baidu. Is it possible to share Google Drive link?

sure, we will share the google drive link soon.

**Comment by FANzhaoxin666** [comment]
> 

please refer to https://github.com/CVCUDA/CV-CUDA

**Comment by linghai06** [comment]
thanks for your sharing. really looking forward to it

**Comment by prakyath-07** [comment]
Any update on the drive or alternative link? @Life93

**Comment by cucdengjunli** [comment]
> Any update on the drive or alternative link? @Life93

google drive has been updated

**Comment by prakyath-07** [comment]
> > Any update on the drive or alternative link? @Life93
> 
> google drive has been updated

Thank you :)
