### ISSUE TITLE
运行 gen_resource_pkg.py 时，Inference_wav2lip_tools 缺失

### ISSUE THREAD

**Issue by chenkaiC4** [psyai-net/CVCUDA_FaceStoreHelper-release#2]
你好，想体验下GPU飞一般的感觉，但按照 readme 的提示，在执行 gen_resource_pkg.py 时，找不到 Inference_wav2lip_tools 包。

查了pip库里没有这个包，应该是本地的一个库吗？这块的代码找不到

**Comment by chenkaiC4** [comment]
```
from Inference_wav2lip_tools import  get_audio_frame_list, load_model, Wav2lip_Dataset
```
这行代码没有作用，删除后可以运行了

**Comment by chenkaiC4** [comment]
补充，运行 gen_resource_pkg.py 时，往 testdata/video_based 文件夹下放一个视频，作为人脸特征提取的素材。

**Comment by cucdengjunli** [comment]
This bug has been fixed
