### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by chenkaiC4** [psyai-net/CVCUDA_FaceStoreHelper-release#3]
https://github.com/psyai-net/CVCUDA_FaceStoreHelper-release/blob/cfc17e07df59eb59279b364afb927acdfbefbe2d/codeformer/basicsr/archs/codeformer_arch.py#L116

这一行代码，运行时报错：

```
The size of tensor a (192) must match the size of tensor b (256) at non-singleton dimension 0
```

其中
```
print(tensor.size())   #[192, 2, 512]
print(pos.size())       # [256, 2, 512])
```

**Comment by cucdengjunli** [comment]
This bug has been fixed
